/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cat_mpl_moodsdk_Insight */

#ifndef _Included_cat_mpl_moodsdk_Insight
#define _Included_cat_mpl_moodsdk_Insight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cat_mpl_moodsdk_Insight
 * Method:    process
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cat_mpl_moodsdk_Insight_process
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cat_mpl_moodsdk_Insight
 * Method:    getTrackingPoints
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cat_mpl_moodsdk_Insight_getTrackingPoints
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
