const char * facs_str = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n"  
    "<facs>\n"
    "\n"
    "  <actionUnits>\n"
    "\n"
    "    <actionUnit code=\"1\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"21\" point2=\"39\" threshold=\"1.5\"/> \n"
    "        <distanceFeature point1=\"22\" point2=\"42\" threshold=\"1.5\"/> \n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"2\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"19\" segment1=\"37,38\" threshold=\"1.5\"/> \n"
    "        <distanceFeature point1=\"24\" segment1=\"43,44\" threshold=\"1.5\"/> \n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"4\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"19\" segment1=\"37,38\" threshold=\"2\" mode=\"compress\" /> \n"
    "        <distanceFeature point1=\"24\" segment1=\"43,44\" threshold=\"2\" mode=\"compress\"/> \n"
    "        <distanceFeature point1=\"19\" segment1=\"41,40\" threshold=\"2\" mode=\"compress\" /> \n"
    "        <distanceFeature point1=\"24\" segment1=\"46,47\" threshold=\"2\" mode=\"compress\"/> \n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"5\">\n"
    "        <distanceFeature segment1=\"37,38\" segment2=\"40,41\" threshold=\"1.5\"/> \n"
    "        <distanceFeature segment1=\"43,44\" segment2=\"46,47\" threshold=\"1.5\"/> \n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"6\">\n"
    "        <distanceFeature segment1=\"37,38\" segment2=\"40,41\" threshold=\"1\" mode=\"compress\"/> \n"
    "        <distanceFeature segment1=\"43,44\" segment2=\"46,47\" threshold=\"1\" mode=\"compress\"/>\n"
    "        <distanceFeature point1=\"48\" point2=\"54\" threshold=\"1\"/> \n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"10\">\n"
    "      <features>\n"
    "        <!-- distanceFeature point1=\"48\" point2=\"54\" threshold=\"1\" mode=\"compress\"/ --> \n"
    "        <distanceFeature point1=\"30\" point2=\"51\" threshold=\"2\" mode=\"compress\"/>\n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"12\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"48\" point2=\"54\" threshold=\"2.1\"/> \n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"15\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"48\" point2=\"64\" threshold=\"1.5\" yOnly=\"true\" mode=\"positive\"/>\n"
    "        <distanceFeature point1=\"54\" point2=\"64\" threshold=\"1.5\" yOnly=\"true\" mode=\"positive\"/>\n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"25\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"8\" point2=\"30\" threshold=\"2\"/> \n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"26\">\n"
    "      <features>\n"
    "        <distanceFeature point1=\"8\" point2=\"30\" threshold=\"3\"/>\n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "    <actionUnit code=\"43\">\n"
    "      <features>\n"
    "        <distanceFeature segment1=\"18,20\" segment2=\"37,38\" threshold=\"1\"/> \n"
    "        <distanceFeature segment1=\"18,20\" segment2=\"40,41\" threshold=\"1\"/> \n"
    "        <distanceFeature segment1=\"23,25\" segment2=\"43,44\" threshold=\"1\"/> \n"
    "        <distanceFeature segment1=\"23,25\" segment2=\"46,47\" threshold=\"1\"/>\n"
    "        <!-- distanceFeature segment1=\"37,38\" segment2=\"40,41\" threshold=\"2\" type=\"compress\"/>\n"
    "        <distanceFeature segment1=\"43,44\" segment2=\"46,47\" threshold=\"2\" type=\"compress\"/ -->\n"
    "      </features>\n"
    "    </actionUnit>\n"
    "\n"
    "  </actionUnits>\n"
    "\n"
    "</facs>\n"
    "";
