const char * mood_str = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n"  
    "<moodLevels detectionWindow=\"100\" auDetectionWindow=\"10\">\n"
    "\n"
    "  <!-- level name=\"Arousal\">\n"
    "    <moods>\n"
    "      <mood code=\"15\" label=\"Arousal\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "    </moods>\n"
    "  </level -->\n"
    "  \n"
    "  <level name=\"Third\">\n"
    "    <moods>\n"
    "      <mood code=\"13\" label=\"Positive\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"12\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"14\" label=\"Negative\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "    </moods>\n"
    "  </level>\n"
    "\n"
    "  <level name=\"Second\">\n"
    "    <moods>\n"
    "      <mood code=\"9\" label=\"Elated\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"10\" label=\"Calm\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"11\" label=\"Anxious2\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"12\" label=\"Bored2\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "    </moods>\n"
    "  </level>\n"
    "\n"
    "  <level name=\"First\">\n"
    "    <moods>\n"
    "      <mood code=\"1\" label=\"Exuberant\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"6\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"2\" label=\"Dependent\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"1\" />\n"
    "	  <actionUnit code=\"2\" />\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"3\" label=\"Relaxed\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"6\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"4\" label=\"Docile\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"1\" />\n"
    "	  <actionUnit code=\"2\" />\n"
    "	  <actionUnit code=\"12\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"5\" label=\"Hostile\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"10\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"6\" label=\"Anxious\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"1\" />\n"
    "	  <actionUnit code=\"2\" />\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"5\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"25\" />\n"
    "	  <actionUnit code=\"26\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"7\" label=\"Bored\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"1\" />\n"
    "	  <actionUnit code=\"2\" />\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "      <mood code=\"8\" label=\"Disdainful\">\n"
    "	<actionUnits>\n"
    "	  <actionUnit code=\"4\" />\n"
    "	  <actionUnit code=\"15\" />\n"
    "	  <actionUnit code=\"43\" />\n"
    "	</actionUnits>\n"
    "      </mood>\n"
    "    </moods>\n"
    "  </level>\n"
    "  \n"
    "</moodLevels>\n"
    "";
